### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [Antonis427/veterondo#1]
It would be great to have this app on F-Droid, which is a kind of Google Play but only including free software apps: https://f-droid.org/

Here are some instructions as to how to add it to the submissions queue: https://f-droid.org/contribute/

**Comment by pizzamaker** [comment]
Hi, I'm confused?

**Comment by Antonis427** [comment]
Hi there, it's probably me who's confused! I've been using github just for a while. I submitted Veterondo to F-Droid. Doesn't this mean that I should close the issue? Sorry, newbie here!

**Comment by pizzamaker** [comment]
Great! It seems it was added. Thanks a lot :)
